# Generated by Django 5.1.1 on 2024-10-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
